[package]
name = "icinga2ctl"
version = "1.0.0-20201207"
authors = ["Andreas Maus <maus@badphish.ypbind.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
